import {StyleSheet} from 'react-native'
import {Colors, Fonts, Metrics} from 'App/Theme'
import ApplicationStyles from 'App/Theme/ApplicationStyles'

export default StyleSheet.create({
  boldTxt: {
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.medium,
  },
  bookmarkContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: Metrics.applyRatio(30),
  },
  businessPasscode: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    marginBottom: Metrics.applyRatio(-10),
    marginHorizontal: Metrics.applyRatio(55),
    textAlign: 'center',
  },
  clearIconStyle: {
    padding: 10,
  },
  codeCellContainer: {
    marginTop: Metrics.applyRatio(30),
    width: Metrics.applyRatio(304),
  },
  codeCellItem: {
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.applyRatio(13.6),
    fontFamily: Fonts.fonts.PoppinsRegular,
    paddingBottom: 1,
  },
  codeInputWrapper: {
    alignItems: 'center',
    height: Metrics.applyRatio(120),
  },
  completeBoldTxt: {
    color: Colors.black,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.bigMedium,
  },
  completeFooterContainer: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  completeTextWrapper: {
    backgroundColor: Colors.paleGrey2,
    borderRadius: Metrics.applyRatio(18),
    marginBottom: Metrics.applyRatio(30),
    marginTop: Metrics.applyRatio(20),
    padding: Metrics.applyRatio(20),
    width: Metrics.applyRatio(280),
  },
  completeTitle: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.regular,
  },
  container: {...ApplicationStyles.screen.container},
  contentContainer: {
    alignItems: 'center',
    flex: 5,
  },
  descriptionBox: {
    color: Colors.grey4,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.xsmall,
  },
  editPasscodeTxt: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.medium,
    marginLeft: Metrics.applyRatio(10),
  },
  expectedCashbackTxt: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsMedium,
    fontSize: Fonts.size.medium,
    textAlign: 'center',
  },
  footerContainer: {
    alignItems: 'center',
    flex: 2,
    paddingBottom: Metrics.applyRatio(20),
  },
  footerDesc: {
    color: Colors.coolGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    lineHeight: Metrics.applyRatio(20),
    marginBottom: Metrics.applyRatio(20),
    textAlign: 'center',
    width: Metrics.applyRatio(238),
  },
  footerTextContent: {
    justifyContent: 'center',
    marginBottom: Metrics.applyRatio(60),
    marginTop: Metrics.applyRatio(91),
  },
  imgContainer: {
    marginBottom: Metrics.applyRatio(63),
    marginTop: Metrics.applyRatio(53),
  },
  inactiveButton: {
    backgroundColor: Colors.lightBlueGrey,
    opacity: 0.6,
  },
  inputStyle: {
    ...ApplicationStyles.inputStyle,
    color: Colors.black1,
    marginBottom: Metrics.applyRatio(5),
    marginTop: Metrics.applyRatio(30),
  },
  invalidText: {
    alignSelf: 'center',
    color: Colors.reddish91,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
    marginBottom: Metrics.applyRatio(10),
    marginTop: Metrics.applyRatio(-40),
  },
  listButtonIcon: {
    ...ApplicationStyles.locationBoxThirdStyle,
  },
  listItem: {
    alignItems: 'center',
    backgroundColor: Colors.greyBackground,
    flexDirection: 'row',
    height: Metrics.applyRatio(57),
    width: Metrics.applyRatio(315),
  },
  listItemButtonList: {flexDirection: 'row', flexWrap: 'wrap', marginTop: Metrics.applyRatio(5)},
  listViewItem: {
    backgroundColor: Colors.white,
    borderRadius: Metrics.applyRatio(20),
    marginHorizontal: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(20),
    padding: Metrics.applyRatio(10),
  },
  listViewItemWithBorder: {
    backgroundColor: Colors.white,
    borderColor: Colors.listCardBorder,
    borderRadius: Metrics.applyRatio(20),
    borderWidth: 1,
    marginHorizontal: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(20),
  },
  moreIcon: {
    height: Metrics.applyRatio(13),
    width: Metrics.applyRatio(10),
  },
  nameStyle: {
    height: Metrics.applyRatio(33),
    margin: Metrics.applyRatio(15),
    width: Metrics.applyRatio(33),
  },
  namesStyle: {flexDirection: 'column'},
  onlineRedemptionCompleteImg: {
    height: Metrics.applyRatio(293),
    width: Metrics.DEVICE_WIDTH,
  },
  orTxt: {
    color: Colors.grey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.bigMedium,
    paddingVertical: Metrics.applyRatio(20),
    textAlign: 'center',
  },
  orderDec: {
    color: Colors.coolGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    textAlign: 'center',
    width: Metrics.applyRatio(274),
  },
  orderTitle: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.h5,
    lineHeight: Metrics.applyRatio(28),
    marginBottom: Metrics.applyRatio(10),
    marginTop: Metrics.applyRatio(40),
    textAlign: 'center',
  },
  passcodeFooterTxt: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    marginHorizontal: Metrics.applyRatio(40),
    textAlign: 'center',
  },
  promotionDisplay: {
    alignSelf: 'center',
    borderColor: Colors.listCardBorder,
    borderRadius: Metrics.applyRatio(15),
    borderStyle: 'solid',
    borderWidth: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    height: Metrics.applyRatio(86),
    width: Metrics.applyRatio(335),
  },
  referralRequestTxt: {
    color: Colors.grey2,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.bigMedium,
    lineHeight: Metrics.applyRatio(23),
    textAlign: 'center',
    width: Metrics.applyRatio(310),
  },
  referreByTxt: {
    borderColor: Colors.listCardBorder,
    borderRadius: Metrics.applyRatio(10),
    borderWidth: 1,
    color: Colors.coolGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    height: Metrics.applyRatio(36),
    lineHeight: Metrics.applyRatio(20),
    margin: Metrics.applyRatio(20),
    paddingHorizontal: Metrics.applyRatio(16),
    paddingVertical: Metrics.applyRatio(8),
    textAlign: 'center',
  },
  roundSearchBar: {
    backgroundColor: Colors.greyBackground,
    borderBottomWidth: 0,
    borderTopWidth: 0,
    height: Metrics.applyRatio(55),
    width: Metrics.applyRatio(315),
  },
  roundSearchText: {
    ...Fonts.style.titleSection,
    color: Colors.brownGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
  },
  scanIcon: {
    maxHeight: Metrics.applyRatio(15),
    maxWidth: Metrics.applyRatio(15),
    minHeight: Metrics.applyRatio(12),
    minWidth: Metrics.applyRatio(12),
    resizeMode: 'contain',
  },
  scanQRcodeTxt: {
    color: Colors.white,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.medium,
    paddingLeft: Metrics.applyRatio(10),
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContentContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollInnerView: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingBottom: Metrics.applyRatio(30),
  },
  semiTitle: {
    alignSelf: 'center',
    color: Colors.black1,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.big,
    marginTop: Metrics.applyRatio(30),
    textAlign: 'center',
  },
  separatorStyle: {
    alignSelf: 'center',
    backgroundColor: Colors.greyDivider,
    height: Metrics.applyRatio(1),
    width: Metrics.applyRatio(275),
  },
  spentTxt: {
    color: Colors.coolGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
    lineHeight: Metrics.applyRatio(17),
    marginBottom: Metrics.applyRatio(5),
    textAlign: 'center',
  },
  stretchableView: {
    alignSelf: 'center',
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.applyRatio(17),
    margin: Metrics.applyRatio(20),
    overflow: 'hidden',
  },
  subtitleStyle: {
    ...Fonts.style.subSectionTitle,
    fontSize: Fonts.size.medium,
    marginBottom: Metrics.applyRatio(10),
    marginHorizontal: Metrics.applyRatio(55),
    textAlign: 'center',
  },
  textBox: {flexDirection: 'column', margin: Metrics.applyRatio(10)},
  titleBox: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsMedium,
    fontSize: Fonts.size.bigMedium,
    width: Metrics.applyRatio(200),
  },
  validationButton: {
    ...ApplicationStyles.buttonContainer,
    marginTop: Metrics.applyRatio(13),
    width: Metrics.applyRatio(172),
  },
  validationText: {
    ...ApplicationStyles.textButton,
  },
  whatsAppIcon: {
    height: Metrics.applyRatio(18),
    width: Metrics.applyRatio(18),
  },
})
