import {StyleSheet} from 'react-native'
import {Colors, Fonts, Metrics} from 'App/Theme'
import ApplicationStyles from 'App/Theme/ApplicationStyles'

export default StyleSheet.create({
  addLocationBtnContainer: {
    alignItems: 'center',
    color: Colors.coolGrey,
    flexDirection: 'row',
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.small,
    justifyContent: 'center',
  },
  addLocationText: {
    color: Colors.grey1,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.bigMedium,
  },
  addLocationTitle: {
    color: Colors.black2,
    fontSize: Fonts.size.big,
  },
  addNewLocationText: {
    ...Fonts.style.clickableTextBold,
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsBold,
    height: Metrics.applyRatio(20),
    marginLeft: Metrics.applyRatio(10),
    width: Metrics.applyRatio(130),
  },
  addNewLocationView: {alignSelf: 'center', marginTop: Metrics.applyRatio(22)},
  addressList: {alignItems: 'center', marginTop: Metrics.applyRatio(30)},
  addressView: {alignItems: 'center', marginTop: Metrics.applyRatio(10)},
  angleIcon: {
    backgroundColor: Colors.greyBackground,
    height: Metrics.GUTTER_WIDTH,
    marginBottom: Metrics.GUTTER_WIDTH * -0.5,
    transform: [{rotate: '45deg'}],
    width: Metrics.GUTTER_WIDTH,
  },
  bigText: {
    color: Colors.black,
    fontSize: Fonts.size.xbig,
    textAlign: 'center',
  },
  boldText: {
    ...Fonts.style.clickableTextBold,
    textAlign: 'center',
  },
  bookmarkContainer: {
    flexDirection: 'row',
    marginBottom: Metrics.applyRatio(50),
  },
  buttonContainer: {
    ...ApplicationStyles.buttonContainer,
    marginTop: Metrics.applyRatio(20),
  },
  buttonTextStyle: {
    ...ApplicationStyles.buttonTitle,
  },
  campaignDetail: {
    alignItems: 'center',
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.GUTTER_WIDTH * 3,
    marginHorizontal: Metrics.GUTTER_WIDTH * 3,
    padding: Metrics.GUTTER_WIDTH * 2,
  },
  campaignTextDetail: {
    justifyContent: 'center',
  },
  captionMargin: {marginTop: Metrics.applyRatio(0), ...Fonts.style.dropDownText},
  checkoutList: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  checkoutListFirstItem: {
    marginTop: Metrics.GUTTER_WIDTH * 2,
  },
  chekIcon: {
    height: Metrics.GUTTER_WIDTH * 2,
    width: Metrics.GUTTER_WIDTH * 2,
  },
  clickableText: {
    ...Fonts.style.clickableText,
  },
  codeCellCenterItem: {
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.applyRatio(13.6),
    fontFamily: Fonts.fonts.PoppinsRegular,
    justifyContent: 'center',
    lineHeight: Metrics.applyRatio(30),
    paddingBottom: 1,
    textAlignVertical: 'center',
  },
  codeCellContainer: {
    marginTop: Metrics.applyRatio(30),
    width: Metrics.applyRatio(304),
  },
  codeCellItem: {
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.applyRatio(13.6),
    fontFamily: Fonts.fonts.PoppinsRegular,
    justifyContent: 'center',
    paddingBottom: 1,
    textAlignVertical: 'center',
  },
  codeInputWrapper: {
    alignItems: 'center',
    height: Metrics.applyRatio(100),
  },
  container: {
    ...ApplicationStyles.screen.container,
  },
  contentContainer: {
    paddingHorizontal: Metrics.applyRatio(35),
    // justifyContent: 'center',
  },
  contentFullContainer: {
    flex: 5,
  },
  datePicker: {
    backgroundColor: Colors.greyBackground,
    borderRadius: 12,
    height: Metrics.applyRatio(55),
    padding: Metrics.GUTTER_WIDTH,
    width: Metrics.applyRatio(315),
  },
  datePickerCustom: {
    alignItems: 'flex-start',
    borderWidth: 0,
    textAlign: 'left',
  },
  datePickerItem: {
    height: Metrics.applyRatio(100),
  },
  dropDownView: {alignItems: 'center', marginTop: Metrics.applyRatio(30)},
  editCampaignBtn: {
    alignItems: 'center',
    backgroundColor: Colors.grey4,
    borderRadius: Metrics.GUTTER_WIDTH * 1.5,
    bottom: Metrics.GUTTER_WIDTH * -1.5,
    height: Metrics.GUTTER_WIDTH * 3,
    position: 'absolute',
    width: Metrics.GUTTER_WIDTH * 3,
  },
  editCampaignImg: {
    backgroundColor: Colors.grey4,
    borderRadius: Metrics.GUTTER_WIDTH * 1.5,
    height: Metrics.GUTTER_WIDTH * 3,
    width: Metrics.GUTTER_WIDTH * 3,
  },
  end: {alignItems: 'flex-end', flexDirection: 'row'},
  fMandarinOrient: {
    ...Fonts.style.addressDes,
    marginTop: Metrics.applyRatio(5),
    width: Metrics.applyRatio(247),
  },
  flatList: {height: '80%'},
  flatMainView: {marginLeft: Metrics.applyRatio(10)},
  flexOne: {flex: 1},
  flexWrap: {
    flexWrap: 'wrap',
  },
  iconSize: {height: Metrics.applyRatio(15), width: Metrics.applyRatio(15)},
  imagePickerButton: {
    ...ApplicationStyles.screen.container,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePickerButtonContainer: {
    alignSelf: 'center',
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.GUTTER_WIDTH * 2,
    height: Metrics.applyRatio(200),
    marginBottom: Metrics.applyRatio(30),
    marginTop: Metrics.applyRatio(30),
    width: Metrics.applyRatio(315),
  },
  imgLeft: {
    marginLeft: Metrics.applyRatio(15),
  },
  inactiveButton: {
    opacity: 0.6,
  },
  inputLocationStyle: {
    ...ApplicationStyles.inputStyle,
  },
  inputStyle: {
    ...ApplicationStyles.inputStyle,
    marginBottom: Metrics.GUTTER_WIDTH * 0.5,
    marginTop: Metrics.GUTTER_WIDTH * 3,
  },
  inputWrapper: {
    backgroundColor: Colors.greyBackground,
    borderRadius: 12,
    justifyContent: 'center',
    padding: Metrics.GUTTER_WIDTH * 0.5,
    width: Metrics.applyRatio(95),
  },
  line: {
    borderColor: Colors.captionBorder,
    borderStyle: 'solid',
    borderWidth: Metrics.applyRatio(0.5),
    height: Metrics.applyRatio(1),
    marginTop: Metrics.applyRatio(9),
    width: Metrics.applyRatio(315),
  },
  link: {color: Colors.brightBlue},
  listBottomSection: {marginVertical: Metrics.GUTTER_WIDTH * 0.3, textAlign: 'center'},
  listBottomSectionText: {fontFamily: Fonts.fonts.PoppinsRegular, fontSize: Fonts.size.xsmall},

  listButtonIcon: {
    ...ApplicationStyles.locationBoxThirdStyle,
  },
  listImgWrapper: {borderRadius: Metrics.GUTTER_WIDTH, marginRight: Metrics.GUTTER_WIDTH},
  listInnerItem: {
    borderBottomColor: Colors.black5,
    borderBottomWidth: Metrics.GUTTER_WIDTH * 0.1,
    flexDirection: 'row',
    padding: Metrics.GUTTER_WIDTH,
  },
  listItemButtonList: {flexDirection: 'row', flexWrap: 'wrap'},
  listViewItem: {
    backgroundColor: Colors.white,
    borderRadius: Metrics.GUTTER_WIDTH * 2,
    marginTop: Metrics.DEVICE_HEIGHT * 0.03,
  },
  listtopsection: {flexDirection: 'row', justifyContent: 'space-between'},
  locationListItem: {
    flexDirection: 'column',
    flex: 1,
    justifyContent: 'space-between',
  },
  locationSelectItem: {
    color: Colors.grey2,
    height: Metrics.applyRatio(55),
    width: Metrics.applyRatio(305),
  },
  locationValue: {
    color: Colors.grey2,
    fontSize: Fonts.size.bigMedium,
    paddingLeft: Metrics.applyRatio(10),
  },
  mapIconCenter: {
    alignSelf: 'center',
  },
  mapMarkIcon: {
    height: Metrics.applyRatio(15),
    marginRight: Metrics.applyRatio(10),
    width: Metrics.applyRatio(11),
  },
  modalBack: {marginTop: Metrics.applyRatio(20)},
  modalBackInner: {
    backgroundColor: Colors.modalBack,
    borderRadius: 2.5,
    height: Metrics.applyRatio(5),
    width: Metrics.applyRatio(30),
  },
  modalContainer: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  modalContent: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderTopLeftRadius: Metrics.applyRatio(25),
    borderTopRightRadius: Metrics.applyRatio(25),
    padding: Metrics.applyRatio(25),
  },
  modalListItem: {
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.applyRatio(20),
    height: Metrics.applyRatio(55),
    justifyContent: 'center',
    marginBottom: Metrics.applyRatio(40),
    padding: Metrics.applyRatio(5),
    textAlign: 'left',
    width: Metrics.applyRatio(315),
  },
  modalMainView: {
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: Metrics.applyRatio(20),
    bottom: 0,
    height: Metrics.applyRatio(409),
    marginBottom: Metrics.applyRatio(1),
    position: 'absolute',
    width: '100%',
  },
  modalTopDash: {
    backgroundColor: Colors.grey1,
    borderRadius: Metrics.applyRatio(12),
    height: Metrics.applyRatio(5),
    width: Metrics.applyRatio(30),
  },
  modalViewMain: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: Colors.blackShadeOpacity2,
  },
  moreIcon: {
    alignItems: 'flex-end',
    margin: Metrics.applyRatio(5),
  },
  multilineInputStyle: {
    backgroundColor: Colors.greyInput,
    borderRadius: Metrics.applyRatio(17),
    marginBottom: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(5),
    minHeight: Metrics.applyRatio(55),
    padding: Metrics.GUTTER_WIDTH,
    textAlignVertical: 'top',
    width: Metrics.applyRatio(333),
  },
  nameTxt: {
    ...Fonts.style.titleSection,
  },
  nextContainer: {
    backgroundColor: Colors.transparent,
    borderTopLeftRadius: Metrics.GUTTER_WIDTH * 2,
    borderTopRightRadius: Metrics.GUTTER_WIDTH * 2,
    flex: 1,
    // justifyContent: 'center',
  },
  noPadding: {
    padding: 0,
  },
  noRecImg: {height: Metrics.applyRatio(183), width: Metrics.applyRatio(300)},
  noRecInnerView: {alignSelf: 'center', flex: 1, justifyContent: 'center'},
  noRecText: {
    ...Fonts.style.subSectionTitle,
    alignSelf: 'center',
    marginTop: Metrics.applyRatio(50),
    textAlign: 'center',
    width: Metrics.applyRatio(214),
  },
  numberInputStyle: {
    borderBottomWidth: 1,
    borderColor: Colors.black5,
    color: Colors.greyDark,
    fontSize: Fonts.size.big,
    justifyContent: 'center',
    padding: 2,
    textAlign: 'center',
  },
  otherTxt: {
    ...Fonts.style.subSectionTitle,
  },
  passCodeBottomText: {
    color: Colors.grey1,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    textAlign: 'center',
  },
  passCodeBottomTextContainer: {
    alignItems: 'center',
    marginVertical: Metrics.GUTTER_WIDTH,
  },
  passCodeInputContainer: {
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  picker: {
    borderColor: Colors.black,
    borderWidth: 1,
    color: Colors.brick,
    height: 150,
    width: 100,
  },
  pickerItem: {
    color: Colors.black,
    fontSize: 20,
  },
  previewNextContainer: {
    alignItems: 'center',
    borderTopLeftRadius: Metrics.GUTTER_WIDTH * 2,
    borderTopRightRadius: Metrics.GUTTER_WIDTH * 2,
    borderWidth: 0,
    flex: 2,
    justifyContent: 'center',
  },
  qrCodeContainer: {
    backgroundColor: Colors.white,
    padding: Metrics.applyRatio(25),
  },
  referButtonWrapper: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    padding: Metrics.GUTTER_WIDTH,
  },
  renderView: {
    alignSelf: 'flex-start',
    flexDirection: 'column',
  },
  salesNum: {
    fontSize: Fonts.size.small,
    padding: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  scrollContentContainer: {},
  sectionTitle: {
    ...Fonts.style.greyInfoUpperCase,
    alignSelf: 'flex-start',
    marginLeft: Metrics.applyRatio(10),
  },
  selectedImageStyle: {
    borderRadius: Metrics.GUTTER_WIDTH * 2,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  shape: {
    alignSelf: 'flex-end',
    height: Metrics.applyRatio(8),
    marginLeft: Metrics.applyRatio(20),
    width: Metrics.applyRatio(8),
  },
  showHideTxt: {
    alignItems: 'center',
    color: Colors.blueValidation,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.medium,
    justifyContent: 'center',
    paddingBottom: Metrics.applyRatio(20),
  },
  sliderSection: {
    marginBottom: Metrics.GUTTER_WIDTH * 2,
    marginTop: Metrics.GUTTER_WIDTH * 3,
    width: Metrics.applyRatio(240),
  },
  sliderWrapper: {
    alignItems: 'center',
  },
  stepContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Metrics.applyRatio(30),
  },
  stepDescription: {
    width: Metrics.applyRatio(278),
  },
  stepTextStyle: {
    color: Colors.grey,
    textAlign: 'center',
  },
  stepTitleStyle: {
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.regular,
    // fontWeight: 'bold',
    textAlign: 'center',
  },
  subCaptionText: {
    ...Fonts.style.subSectionTitle,
  },
  targetLocationItem: {
    alignItems: 'center',
    borderColor: Colors.black5,
    borderRadius: Metrics.GUTTER_WIDTH * 2,
    borderWidth: 1,
    flexDirection: 'row',
    height: Metrics.HEIGHT_FOR_TABS,
    justifyContent: 'space-between',
    margin: Metrics.GUTTER_WIDTH,
    paddingHorizontal: Metrics.GUTTER_WIDTH * 2,
  },
  templateBtnContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  templateIcon: {
    height: Metrics.GUTTER_WIDTH * 2,
    marginRight: Metrics.GUTTER_WIDTH,
    width: Metrics.GUTTER_WIDTH * 1.7,
  },
  text: {
    textAlign: 'center',
  },
  title: {
    ...Fonts.style.title,
    marginTop: Metrics.applyRatio(20),
  },
  titleContainer: {
    marginBottom: Metrics.applyRatio(38),
    marginTop: Metrics.applyRatio(20),
  },
  toolTipText: {
    color: Colors.white,
    fontSize: Fonts.size.small,
    textAlign: 'left',
  },
  uncheckIcon: {
    opacity: 0.1,
  },
  validationButton: {
    ...ApplicationStyles.buttonContainer,
  },
  validationText: {
    ...ApplicationStyles.textButton,
  },
  waveIcon: {
    height: Metrics.GUTTER_WIDTH * 0.8,
    width: Metrics.GUTTER_WIDTH * 5,
  },
  waveIconContainer: {
    alignItems: 'center',
    marginBottom: Metrics.GUTTER_WIDTH * 2,
    marginTop: Metrics.GUTTER_WIDTH * 4,
  },
})
