import {StyleSheet} from 'react-native'
import {Fonts, ApplicationStyles, Colors, Metrics} from 'App/Theme'

export default StyleSheet.create({
  addressTxt: {
    color: Colors.coolGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    marginBottom: Metrics.applyRatio(10),
  },
  bannerContainer: {
    backgroundColor: Colors.white,
    borderRadius: Metrics.applyRatio(10),
    padding: Metrics.applyRatio(20),
    paddingLeft: Metrics.applyRatio(10),
    margin: Metrics.applyRatio(20),
    flexDirection: 'row',
  },
  bannerTitle: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.medium,
  },
  bannerTxt: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
  },
  bannerTxtContainter: {
    flex: 1,
    paddingLeft: Metrics.applyRatio(10),
  },
  boldTxt: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.small,
  },
  buttonContainer: {
    ...ApplicationStyles.buttonContainer,
    marginBottom: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(30),
  },
  cardItem: {
    flexDirection: 'column',
    marginHorizontal: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(20),
  },
  // categoryName: {},
  categoryName: {
    color: Colors.black1,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.small,
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
    width: Metrics.applyRatio(60),
  },
  centerError: {alignItems: 'center', justifyContent: 'center'},
  clearIconStyle: {
    paddingBottom: Metrics.applyRatio(10),
  },
  container: {
    ...ApplicationStyles.screen.container,
    backgroundColor: Colors.greyBackground,
    overflow: 'hidden',
  },
  earnText: {
    ...Fonts.style.subSectionTitle,
    fontSize: Fonts.size.xsmall,
  },
  emptyStyle: {
    alignItems: 'center',
    alignSelf: 'center',
    flexWrap: 'wrap',
    height: Metrics.applyRatio(400),
    justifyContent: 'center',
    width: Metrics.applyRatio(238),
  },
  emptyText: {
    color: Colors.blueyGrey,
    // fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.bigMedium,
    fontStyle: 'italic', // TODO: waiting for PoppinsItalic
    letterSpacing: Fonts.letterSpacing.xSmall,
    marginBottom: Metrics.applyRatio(30),
    textAlign: 'center',
  },
  error: {
    ...Fonts.style.normal,
    marginBottom: 5,
    textAlign: 'center',
  },
  flatListHeaderStyle: {flexDirection: 'row'},
  flexOne: {flex: 1},
  instructions: {
    ...Fonts.style.normal,
    fontStyle: 'italic',
    marginBottom: 5,
    textAlign: 'center',
  },
  listBottomSection: {marginBottom: Metrics.applyRatio(5)},
  listBottomSectionText: {
    color: Colors.grey4,
    fontFamily: Fonts.fonts.PoppinsMedium,
    fontSize: Fonts.size.xsmall,
  },
  listButtonIcon: {
    ...ApplicationStyles.locationBoxThirdStyle,
  },
  listImgWrapper: {borderRadius: Metrics.applyRatio(10), marginRight: Metrics.applyRatio(10)},
  listInnerItem: {
    flexDirection: 'row',
    padding: Metrics.applyRatio(10),
  },
  listItemButtonList: {flexDirection: 'row', flexWrap: 'wrap'},
  listTopSection: {
    alignItems: 'center',
    flexDirection: 'row',
    height: Metrics.applyRatio(23),
    justifyContent: 'space-between',
  },
  listTopSectionText: {
    color: Colors.black,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.bigMedium,
    lineHeight: Metrics.applyRatio(23),
    width: Metrics.applyRatio(200),
  },
  listViewItem: {
    backgroundColor: Colors.white,
    borderRadius: Metrics.applyRatio(20),
    height: Metrics.applyRatio(86),
    marginVertical: Metrics.applyRatio(10),
  },
  loading: {
    ...Fonts.style.normal,
    marginBottom: 5,
    textAlign: 'center',
  },
  logo: {
    height: '100%',
    width: '100%',
  },
  margins: {
    marginBottom: Metrics.applyRatio(10),
    marginLeft: Metrics.applyRatio(10),
    marginRight: Metrics.applyRatio(10),
    marginTop: Metrics.applyRatio(10),
  },
  mockBusinessIcon: {
    backgroundColor: Colors.greyLoading,
    borderRadius: Metrics.applyRatio(14),
    height: Metrics.applyRatio(38),
    width: Metrics.applyRatio(38),
  },
  mockContainer: {
    flexDirection: 'row',
    marginHorizontal: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(20),
  },
  mockLocation: {
    backgroundColor: Colors.greyLoading,
    borderRadius: Metrics.applyRatio(12),
    height: Metrics.applyRatio(18),
    marginLeft: Metrics.applyRatio(10),
    marginTop: Metrics.applyRatio(4),
    width: Metrics.applyRatio(50),
  },
  mockLocationsContainer: {
    flexDirection: 'row',
    marginHorizontal: Metrics.applyRatio(20),
  },
  mockName: {
    backgroundColor: Colors.greyLoading,
    borderRadius: Metrics.applyRatio(9),
    height: Metrics.applyRatio(16),
    width: Metrics.applyRatio(99),
  },
  mockNameBottom: {
    backgroundColor: Colors.greyLoading,
    borderRadius: Metrics.applyRatio(9),
    height: Metrics.applyRatio(16),
    marginTop: Metrics.applyRatio(4),
    width: Metrics.applyRatio(99),
  },
  mockNameContainer: {
    flexDirection: 'column',
    marginLeft: Metrics.applyRatio(10),
  },
  mockPromoImage: {
    backgroundColor: Colors.greyLoading,
    borderRadius: Metrics.applyRatio(25),
    height: Metrics.applyRatio(200),
    marginLeft: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(20),
    width: Metrics.applyRatio(334),
  },
  mockPromoSubtitle: {
    backgroundColor: Colors.greyLoading,
    borderRadius: Metrics.applyRatio(9),
    height: Metrics.applyRatio(23),
    marginLeft: Metrics.applyRatio(30),
    width: Metrics.applyRatio(243),
  },
  mockPromoTitle: {
    backgroundColor: Colors.greyLoading,
    borderRadius: Metrics.applyRatio(9),
    height: Metrics.applyRatio(23),
    marginLeft: Metrics.applyRatio(10),
    width: Metrics.applyRatio(243),
  },
  mockTitleContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: Metrics.applyRatio(20),
  },
  mockcategoryIcon: {
    backgroundColor: Colors.greyLoading,
    borderRadius: Metrics.applyRatio(14),
    height: Metrics.applyRatio(29),
    marginTop: Metrics.applyRatio(10),
    width: Metrics.applyRatio(29),
  },
  mockcategoryIconContainer: {
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    flex: 1,
  },
  moreIcon: {
    height: Metrics.applyRatio(20),
    width: Metrics.applyRatio(20),
  },
  moreIconDetail: {
    alignItems: 'center',
  },
  moreIconView: {
    alignItems: 'flex-end',
    alignSelf: 'flex-end',
    flex: 1,
    marginRight: Metrics.applyRatio(-25),
  },
  nameTxt: {
    ...Fonts.style.titleSection,
  },
  opsNoText: {
    color: Colors.black1,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
    letterSpacing: Fonts.letterSpacing.xSmall,
    marginLeft: Metrics.applyRatio(50),
  },
  otherTxt: {
    ...Fonts.style.subSectionTitle,
  },
  promotionName: {
    ...Fonts.style.promotionName,
  },
  referButtonWrapper: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    padding: Metrics.applyRatio(10),
  },
  referIcon: {
    alignSelf: 'center',
    backgroundColor: Colors.white,
    borderRadius: Metrics.applyRatio(14),
    height: Metrics.applyRatio(38),
    margin: 5,
    width: Metrics.applyRatio(38),
  },
  referIconView: {width: Metrics.applyRatio(23)},
  referImg: {
    borderRadius: Metrics.applyRatio(8),
    height: Metrics.applyRatio(66),
    width: Metrics.applyRatio(66),
  },
  referInnerView: {
    alignItems: 'center',
    flexDirection: 'row',
    height: Metrics.applyRatio(50),
    marginHorizontal: Metrics.applyRatio(20),
  },
  referNameView: {
    alignSelf: 'center',
    marginLeft: Metrics.applyRatio(20),
    width: Metrics.applyRatio(230),
  },
  referNow: {color: Colors.blueValidation, fontSize: Fonts.size.medium},
  referView: {flex: 1, flexDirection: 'column', marginTop: Metrics.applyRatio(20)},
  result: {
    ...Fonts.style.normal,
    marginBottom: 5,
    textAlign: 'center',
  },
  searchBar: {
    backgroundColor: Colors.transparent,
    borderBottomColor: Colors.greyDivider,
    borderTopColor: Colors.transparent,
    flex: 1,
    height: Metrics.applyRatio(40),
    marginHorizontal: Metrics.applyRatio(20),
  },
  searchContent: {
    flex: 1,
    marginTop: Metrics.applyRatio(-50),
  },
  searchPage: {
    backgroundColor: Colors.greyBackground,
    bottom: 0,
    flex: 1,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  separatorStyle: {
    alignSelf: 'center',
    backgroundColor: Colors.greyDivider,
    height: Metrics.applyRatio(1),
    width: Metrics.applyRatio(275),
  },
  text: {
    ...Fonts.style.normal,
    marginBottom: 5,
    textAlign: 'center',
  },
  title: {
    ...Fonts.style.message,
  },
  userIcon: {
    height: Metrics.applyRatio(50),
    width: Metrics.applyRatio(50),
  },
})
