import {Dimensions, Platform, StyleSheet} from 'react-native'
import {Colors, Fonts, Metrics} from 'App/Theme'
import ApplicationStyles from 'App/Theme/ApplicationStyles'

export default StyleSheet.create({
  addLocationBtnContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: Metrics.applyRatio(30),
  },
  addLocationItemTxt: {
    color: Colors.black1,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
  },
  addLocationOnlineItemTxt: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.xsmall,
  },
  addLocationText: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.bigMedium,
  },
  addLocationTitle: {
    color: Colors.black2,
    fontSize: Fonts.size.big,
  },
  addNewLocationText: {
    ...Fonts.style.clickableTextBold,
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsBold,
    height: Metrics.applyRatio(20),
    marginLeft: Metrics.applyRatio(10),
    width: Metrics.applyRatio(130),
  },
  addNewLocationView: {alignSelf: 'center', marginTop: Metrics.applyRatio(22)},
  addressList: {alignItems: 'center', marginTop: Metrics.applyRatio(30)},
  addressView: {alignItems: 'center', marginTop: Metrics.applyRatio(10)},
  angleIcon: {
    backgroundColor: Colors.greyBackground,
    height: Metrics.applyRatio(10),
    marginBottom: Metrics.applyRatio(-5),
    transform: [{rotate: '45deg'}],
    width: Metrics.applyRatio(10),
  },
  bigText: {
    color: Colors.black,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.xbig,
    textAlign: 'center',
  },
  bodyFooterSection: {
    alignItems: 'center',
    marginHorizontal: Metrics.applyRatio(3),
    marginVertical: Metrics.applyRatio(15),
  },
  boldText: {
    ...Fonts.style.clickableTextBold,
    textAlign: 'center',
  },
  bookmarkContainer: {
    flexDirection: 'row',
    marginTop: Metrics.applyRatio(20),
  },
  bottomDescTxt: {
    color: Colors.coolGrey,
    fontFamily: Fonts.fonts.PoppinsMedium,
    fontSize: Fonts.size.medium,
    textAlign: 'center',
  },
  bottomIconTxt: {
    fontSize: Fonts.size.medium,
    marginBottom: Metrics.applyRatio(10),
    marginTop: Metrics.applyRatio(64),
    textAlign: 'center',
  },
  broaderInnerView: {
    alignItems: 'center',
    marginTop: Metrics.applyRatio(51),
  },
  buttonContainer: {
    ...ApplicationStyles.buttonContainer,
    marginTop: Metrics.applyRatio(20),
  },
  buttonTextStyle: {
    ...ApplicationStyles.buttonTitle,
  },
  campaignDetail: {
    alignItems: 'center',
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.applyRatio(30),
    marginHorizontal: Metrics.applyRatio(40),
    padding: Metrics.applyRatio(20),
  },
  campaignTextDetail: {
    justifyContent: 'center',
  },
  captionEg: {
    alignSelf: 'flex-start',
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    marginLeft: Metrics.applyRatio(10),
    padding: Metrics.applyRatio(10),
  },
  captionMargin: {marginTop: Metrics.applyRatio(0), ...Fonts.style.dropDownText},
  checkoutList: {
    flexDirection: 'row',
  },
  checkoutListFirstItem: {
    alignItems: 'center',
    marginTop: Metrics.applyRatio(20),
  },
  chekIcon: {
    height: Metrics.applyRatio(18),
    width: Metrics.applyRatio(18),
  },
  clickableText: {
    ...Fonts.style.clickableText,
  },
  codeCellContainer: {
    marginTop: Metrics.applyRatio(30),
    width: Metrics.applyRatio(304),
  },
  codeCellItem: {
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.applyRatio(13.6),
    fontFamily: Fonts.fonts.PoppinsRegular,
    paddingBottom: 1,
  },
  codeInputWrapper: {
    alignItems: 'center',
    height: Metrics.applyRatio(120),
  },
  container: {
    ...ApplicationStyles.screen.container,
  },
  contentContainer: {
    ...ApplicationStyles.screen.container,
    flex: 5,
    paddingHorizontal: Metrics.applyRatio(20),
    // justifyContent: 'center',
  },
  contentFullContainer: {
    ...ApplicationStyles.screen.container,
    flex: 5,
  },
  customSliderContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom:
      Platform.OS === 'ios'
        ? Dimensions.get('screen').height > 736
          ? Metrics.applyRatio(-12)
          : Metrics.applyRatio(-5)
        : Metrics.applyRatio(-5),
    marginTop:
      Platform.OS === 'ios'
        ? Dimensions.get('screen').height > 736
          ? Metrics.applyRatio(24)
          : Metrics.applyRatio(10)
        : Metrics.applyRatio(10),
    paddingBottom: Metrics.applyRatio(20),
    paddingTop: Metrics.applyRatio(20),
  },
  customSliderStyle: {
    height: 2,
    width: Metrics.applyRatio(37.5),
  },
  datePicker: {
    backgroundColor: Colors.greyBackground,
    borderRadius: 12,
    height: Metrics.applyRatio(55),
    padding: Metrics.applyRatio(10),
    width: Metrics.applyRatio(315),
  },
  datePickerCustom: {
    alignItems: 'flex-start',
    borderWidth: 0,
    textAlign: 'left',
  },
  datePickerItem: {
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    height: Metrics.applyRatio(100),
  },
  datePickerTxt: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
    marginBottom: Metrics.applyRatio(-8),
    paddingLeft: Metrics.applyRatio(10),
    position: 'relative',
    zIndex: 22,
  },
  dropDownView: {alignItems: 'center', marginTop: Metrics.applyRatio(30)},
  editCampaignBtn: {
    alignItems: 'center',
    backgroundColor: Colors.grey4,
    borderRadius: Metrics.applyRatio(15),
    bottom: Metrics.applyRatio(-15),
    height: Metrics.applyRatio(29),
    position: 'absolute',
    width: Metrics.applyRatio(29),
  },
  editCampaignImg: {
    backgroundColor: Colors.grey4,
    borderRadius: Metrics.applyRatio(15),
    height: Metrics.applyRatio(29),
    width: Metrics.applyRatio(29),
  },
  editPasscodeTxt: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.bigMedium,
  },
  editPromotionContainer: {
    marginTop: Metrics.applyRatio(20),
    textAlign: 'center',
  },
  end: {alignItems: 'flex-end', flexDirection: 'row'},
  fMandarinOrient: {
    ...Fonts.style.addressDes,
    marginTop: Metrics.applyRatio(5),
    width: Metrics.applyRatio(247),
  },
  finalText: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    textAlign: 'center',
  },
  flatList: {height: '80%'},
  flatMainView: {marginLeft: Metrics.applyRatio(10)},
  flexOne: {flex: 1},
  flexOneText: {
    color: Colors.blueyGrey,
    flex: 1,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
  },
  flexWrap: {
    flexWrap: 'wrap',
  },
  iconSize: {height: Metrics.applyRatio(15), width: Metrics.applyRatio(15)},
  imagePickerButton: {
    ...ApplicationStyles.screen.container,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePickerButtonContainer: {
    alignSelf: 'center',
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.applyRatio(20),
    height: Metrics.applyRatio(200),
    marginBottom: Metrics.applyRatio(10),
    marginTop: Metrics.applyRatio(30),
    width: Metrics.applyRatio(315),
  },
  imgLeft: {
    marginLeft: Metrics.applyRatio(15),
  },
  inactiveButton: {
    opacity: 0.6,
  },
  inactiveSlider: {
    backgroundColor: Colors.greyBackground,
    flex: 1,
    height: 2,
  },
  inputLocationStyle: {
    ...ApplicationStyles.inputStyle,
  },
  inputStyle: {
    ...ApplicationStyles.inputStyle,
    color: Colors.black1,
    marginBottom: Metrics.applyRatio(5),
    marginTop: Metrics.applyRatio(30),
  },
  inputWrapper: {
    backgroundColor: Colors.greyBackground,
    borderRadius: 12,
    justifyContent: 'center',
    padding: Metrics.applyRatio(5),
    width: Metrics.applyRatio(95),
  },

  italicFont: {
    fontFamily: Fonts.fonts.PoppinsItalic,
  },
  line: {
    borderColor: Colors.captionBorder,
    borderStyle: 'solid',
    borderWidth: Metrics.applyRatio(0.5),
    height: Metrics.applyRatio(1),
    marginTop: Metrics.applyRatio(9),
    width: Metrics.applyRatio(315),
  },
  link: {color: Colors.brightBlue},
  listBottomSection: {marginVertical: Metrics.applyRatio(4), textAlign: 'center'},
  listBottomSectionText: {
    color: Colors.grey4,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.xsmall,
  },
  listButtonIcon: {
    ...ApplicationStyles.locationBoxSecondStyle,
  },
  listImgWrapper: {borderRadius: Metrics.applyRatio(10), marginRight: Metrics.applyRatio(10)},
  listInnerItem: {
    borderBottomColor: Colors.black5,
    borderBottomWidth: Metrics.applyRatio(1),
    flexDirection: 'row',
    padding: Metrics.applyRatio(10),
  },
  listItemButtonList: {flexDirection: 'row', flexWrap: 'wrap'},
  listViewItem: {
    backgroundColor: Colors.white,
    borderRadius: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(40),
  },
  listtopsection: {flexDirection: 'row', justifyContent: 'space-between'},
  locationListItem: {
    flexDirection: 'column',
    flex: 1,
    justifyContent: 'space-between',
  },
  locationSelectItem: {
    color: Colors.grey2,
    height: Metrics.applyRatio(55),
    width: Metrics.applyRatio(305),
  },
  locationValue: {
    color: Colors.grey2,
    fontSize: Fonts.size.bigMedium,
    paddingLeft: Metrics.applyRatio(10),
  },
  mapIconCenter: {
    alignSelf: 'center',
  },
  mapMarkIcon: {
    height: Metrics.applyRatio(15),
    marginRight: Metrics.applyRatio(10),
    width: Metrics.applyRatio(11),
  },
  modalBack: {marginTop: Metrics.applyRatio(20)},
  modalBackInner: {
    backgroundColor: Colors.modalBack,
    borderRadius: 2.5,
    height: Metrics.applyRatio(5),
    width: Metrics.applyRatio(30),
  },
  modalContainer: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  modalContent: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderTopLeftRadius: Metrics.applyRatio(25),
    borderTopRightRadius: Metrics.applyRatio(25),
    padding: Metrics.applyRatio(25),
  },
  modalListItem: {
    backgroundColor: Colors.greyBackground,
    borderRadius: Metrics.applyRatio(20),
    height: Metrics.applyRatio(55),
    justifyContent: 'center',
    marginBottom: Metrics.applyRatio(40),
    padding: Metrics.applyRatio(5),
    textAlign: 'left',
    width: Metrics.applyRatio(315),
  },
  modalMainView: {
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderRadius: Metrics.applyRatio(20),
    bottom: 0,
    height: Metrics.applyRatio(409),
    marginBottom: Metrics.applyRatio(1),
    position: 'absolute',
    width: '100%',
  },
  modalTopDash: {
    backgroundColor: Colors.grey1,
    borderRadius: Metrics.applyRatio(12),
    height: Metrics.applyRatio(5),
    width: Metrics.applyRatio(30),
  },
  modalViewMain: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: Colors.blackShadeOpacity2,
  },
  moreIcon: {
    alignItems: 'flex-end',
    margin: Metrics.applyRatio(5),
  },
  multilineDescInputStyle: {
    backgroundColor: Colors.greyInput,
    borderRadius: Metrics.applyRatio(17),
    color: Colors.black1,
    fontFamily: Fonts.fonts.PoppinsRegular,
    height: Metrics.applyRatio(264),
    marginBottom: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(5),
    minHeight: Metrics.applyRatio(55),
    padding: Metrics.applyRatio(20),
    paddingTop: Metrics.applyRatio(19),
    textAlignVertical: 'top',
    width: Metrics.applyRatio(333),
  },
  multilineInputStyle: {
    backgroundColor: Colors.greyInput,
    borderRadius: Metrics.applyRatio(17),
    color: Colors.black1,
    fontFamily: Fonts.fonts.PoppinsRegular,
    height: Metrics.applyRatio(261),
    marginBottom: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(5),
    minHeight: Metrics.applyRatio(55),
    padding: Metrics.applyRatio(20),
    paddingTop: Metrics.applyRatio(19),
    textAlignVertical: 'top',
    width: Metrics.applyRatio(333),
  },
  nameTxt: {
    ...Fonts.style.titleSection,
    fontSize: Fonts.size.bigMedium,
  },
  nextContainer: {
    backgroundColor: Colors.transparent,
    borderTopLeftRadius: Metrics.applyRatio(20),
    borderTopRightRadius: Metrics.applyRatio(20),
    flex: 1,
    justifyContent: 'flex-end',
    paddingBottom: Metrics.applyRatio(60),
  },
  noPadding: {
    padding: 0,
  },
  noRecImg: {height: Metrics.applyRatio(183), width: Metrics.applyRatio(300)},
  noRecInnerView: {alignSelf: 'center', flex: 1, justifyContent: 'center'},
  noRecText: {
    ...Fonts.style.subSectionTitle,
    alignSelf: 'center',
    marginTop: Metrics.applyRatio(50),
    textAlign: 'center',
    width: Metrics.applyRatio(214),
  },
  numberInputStyle: {
    borderBottomWidth: 1,
    borderColor: Colors.black5,
    color: Colors.greyDark,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.big,
    justifyContent: 'center',
    padding: 2,
    textAlign: 'center',
  },
  onlySelectReferralCatContainer: {
    marginBottom: Metrics.applyRatio(20),
    paddingHorizontal: Metrics.applyRatio(40),
  },
  otherTxt: {
    ...Fonts.style.subSectionTitle,
  },
  passCodeBottomText: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    textAlign: 'center',
    width: Metrics.applyRatio(262),
  },
  passCodeBottomTextContainer: {
    alignItems: 'center',
    marginHorizontal: Metrics.applyRatio(10),
    marginTop: Metrics.applyRatio(20),
  },
  passCodeInputContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  picker: {
    borderColor: Colors.black,
    borderWidth: 1,
    color: Colors.brick,
    height: 150,
    width: 100,
  },
  pickerIcon: {
    backgroundColor: Colors.transparent,
    borderLeftColor: Colors.transparent,
    borderLeftWidth: Metrics.applyRatio(7),
    borderRightColor: Colors.transparent,
    borderRightWidth: Metrics.applyRatio(7),
    borderTopColor: Colors.blueyGrey,
    borderTopWidth: Metrics.applyRatio(7),
    height: Metrics.applyRatio(0),
    width: Metrics.applyRatio(0),
  },
  pickerItem: {
    color: Colors.black,
    fontSize: 20,
  },
  previewNextContainer: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderTopLeftRadius: Metrics.applyRatio(20),
    borderTopRightRadius: Metrics.applyRatio(20),
    borderWidth: 0,
    flex: 1.5,
    justifyContent: 'flex-end',
    paddingBottom: Metrics.applyRatio(60),
    paddingTop: Metrics.applyRatio(20),
  },
  pricingTxt: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.fonts.small,
  },
  promoPasscodeImg: {
    height: Metrics.applyRatio(236),
    marginVertical: Metrics.applyRatio(30),
    width: Metrics.applyRatio(236),
  },
  redeemDesc: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.medium,
    textAlign: 'center',
  },
  redeemImg: {
    height: Metrics.applyRatio(76),
    marginTop: Metrics.applyRatio(14),
    width: Metrics.applyRatio(134),
  },
  redeemInnerView: {
    alignItems: 'center',
    borderColor: Colors.lightBlueGrey,
    borderRadius: Metrics.applyRatio(20),
    borderWidth: Metrics.applyRatio(2),
    justifyContent: 'center',
    marginBottom: Metrics.applyRatio(20),
    padding: Metrics.applyRatio(20),
  },
  redeemSelected: {
    borderColor: Colors.brightBlue,
  },
  redeemTitle: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsMedium,
    fontSize: Fonts.size.big,
    marginBottom: Metrics.applyRatio(10),
    marginTop: Metrics.applyRatio(20),
    textAlign: 'center',
  },
  referButtonWrapper: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    padding: Metrics.applyRatio(10),
  },
  referralCatDesc: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
  },
  referralCatListItem: {
    alignItems: 'center',
    // borderColor: Colors.greyDivider,
    // borderRadius: Metrics.applyRatio(20),
    // borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: Metrics.applyRatio(10),
    // padding: Metrics.applyRatio(20),
  },
  referralCatTitle: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.h2inter,
    lineHeight: Metrics.applyRatio(56),
    textAlign: 'center',
  },
  referralCatTxtContent: {
    paddingLeft: Metrics.applyRatio(20),
    width: Metrics.applyRatio(207),
  },
  referralFeeTxt: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsMedium,
    fontSize: Fonts.size.xsmall,
  },
  referralPercentContent: {
    backgroundColor: Colors.paleGrey2,
    borderRadius: Metrics.applyRatio(18),
    padding: Metrics.applyRatio(10),
    width: Metrics.applyRatio(88),
  },
  renderView: {
    alignSelf: 'flex-start',
    flexDirection: 'column',
  },
  salesNum: {
    fontSize: Fonts.size.xsmall,
    padding: 2,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  scrollContainer: {
    marginBottom: Metrics.applyRatio(20),
  },
  sectionTitle: {
    ...Fonts.style.greyInfoUpperCase,
    alignSelf: 'flex-start',
    marginLeft: Metrics.applyRatio(10),
  },
  selectTemplate: {
    ...Fonts.style.messageBold,
    color: Colors.blueyGrey,
    textAlign: 'center',
  },
  selectedImageStyle: {
    borderRadius: Metrics.GUTTER_WIDTH * 2,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  shape: {
    alignSelf: 'flex-end',
    height: Metrics.applyRatio(8),
    marginLeft: Metrics.applyRatio(20),
    width: Metrics.applyRatio(8),
  },
  sliderSection: {
    marginBottom: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(30),
    width: Metrics.applyRatio(240),
  },
  sliderWrapper: {
    alignItems: 'center',
  },
  stepContainer: {
    ...ApplicationStyles.screen.container,
    alignItems: 'center',
    flex: 1.5,
    justifyContent: 'center',
  },
  stepDarkDescription: {
    color: Colors.black,
    marginVertical: Metrics.applyRatio(10),
    width: Metrics.applyRatio(296),
  },
  stepDescription: {
    color: Colors.blueyGrey,
    marginVertical: Metrics.applyRatio(10),
    width: Metrics.applyRatio(296),
  },
  stepTextStyle: {
    color: Colors.grey,
    textAlign: 'center',
  },
  stepTitleStyle: {
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.regular,
    // fontWeight: 'bold',
    textAlign: 'center',
  },
  subCaptionText: {
    ...Fonts.style.subSectionTitle,
  },
  targetLocationItem: {
    alignItems: 'center',
    borderColor: Colors.black5,
    borderRadius: Metrics.applyRatio(20),
    borderWidth: 1,
    flexDirection: 'row',
    height: Metrics.HEIGHT_FOR_TABS,
    justifyContent: 'space-between',
    marginHorizontal: Metrics.applyRatio(20),
    marginVertical: Metrics.applyRatio(10),
    paddingHorizontal: Metrics.applyRatio(20),
  },
  targetTxtContent: {
    alignItems: 'center',
  },
  templateBtnContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(30),
  },
  templateIcon: {
    height: Metrics.applyRatio(16),
    marginRight: Metrics.applyRatio(10),
    width: Metrics.applyRatio(14),
  },
  text: {
    color: Colors.blueyGrey,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
    textAlign: 'center',
  },
  title: {
    ...Fonts.style.title,
    marginTop: Metrics.applyRatio(20),
  },
  titleContainer: {
    marginBottom: Metrics.applyRatio(38),
    marginTop: Metrics.applyRatio(20),
  },
  toolTipText: {
    color: Colors.white,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
    margin: Metrics.applyRatio(10),
    textAlign: 'justify',
  },
  uncheckIcon: {
    opacity: 0.1,
  },
  validationButton: {
    ...ApplicationStyles.buttonContainer,
  },
  validationText: {
    ...ApplicationStyles.textButton,
    fontSize: Fonts.size.bigMedium,
  },
  waveIcon: {
    height: Metrics.applyRatio(7),
    width: Metrics.applyRatio(47),
  },
  waveIconContainer: {
    alignItems: 'center',
    marginBottom: Metrics.applyRatio(20),
    marginTop: Metrics.applyRatio(40),
  },
})
