<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use doctrine\GraphQLite\Annotations\Type;

use App\Model\Generated\AbstractCustomer;

/**
 * The Customer class maps the 'customers' table in database.
 * @Type
 */
class Customer extends AbstractCustomer
{
    public const ambassador_ID = '2'; // TODO: can be fragile, keep an eye on this

    /**
     * @return bool
     */
    public function isambassador(): bool
    {
        return $this->getId() === self::ambassador_ID;
    }
}
