<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use doctrine\GraphQLite\Annotations\Type;

use App\Model\Generated\AbstractCustomerPayment;

/**
 * The CustomerPayment class maps the 'customer_payments' table in database.
 * @Type
 */
class CustomerPayment extends AbstractCustomerPayment
{
}
