<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use doctrine\GraphQLite\Annotations\Type;

use App\Model\Generated\AbstractDistrict;

/**
 * The District class maps the 'districts' table in database.
 * @Type
 */
class District extends AbstractDistrict
{
}
