<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractMessageTranslation;

/**
 * The MessageTranslation class maps the 'message_translations' table in database.
 */
class MessageTranslation extends AbstractMessageTranslation
{
}
