<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use doctrine\GraphQLite\Annotations\Type;

use App\Model\Generated\AbstractOfflinePromoPricing;

/**
 * The OfflinePromoPricing class maps the 'offline_promo_pricing' table in database.
 * @Type
 */
class OfflinePromoPricing extends AbstractOfflinePromoPricing
{
}
