<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use doctrine\GraphQLite\Annotations\Type;

use App\Model\Generated\AbstractPendingOnlineRedemption;

/**
 * The PendingOnlineRedemption class maps the 'pending_online_redemption' table in database.
 * @Type
 */
class PendingOnlineRedemption extends AbstractPendingOnlineRedemption
{
}
