<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use doctrine\GraphQLite\Annotations\Type;

use App\Model\Generated\AbstractRefer;

/**
 * The Refer class maps the 'refers' table in database.
 * @Type
 */
class Refer extends AbstractRefer
{
}
