<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractRoleRight;
use doctrine\GraphQLite\Annotations\Type;

/**
 * The RoleRight class maps the 'roles_rights' table in database.
 * @Type
 */
class RoleRight extends AbstractRoleRight
{
}
