<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use doctrine\GraphQLite\Annotations\Type;

use App\Model\Generated\AbstractSubCategoryCustomerAverageSpending;

/**
 * The SubCategoryCustomerAverageSpending class maps the 'sub_category_customer_average_spending' table in database.
 * @Type
 */
class SubCategoryCustomerAverageSpending extends AbstractSubCategoryCustomerAverageSpending
{
}
