<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractTransaction;
use doctrine\GraphQLite\Annotations\Type;
use function Safe\substr;

/**
 * The Transaction class maps the 'transactions' table in database.
 * @Type
 */
class Transaction extends AbstractTransaction
{
    /**
     * The constructor takes all compulsory arguments.
     *
     * @param \App\Model\Customer $user
     * @throws \Exception
     */
    public function __construct(\App\Model\Customer $user)
    {
        parent::__construct($user);
        $digits = 7;
        $randomString = substr(str_shuffle(str_repeat($x = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', (int)ceil($digits / strlen($x)))), 1, $digits);
        $this->setUuid($randomString);
    }
}
