<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use App\Model\Generated\AbstractUser;
use doctrine\GraphQLite\Annotations\Type;

/**
 * The User class maps the 'users' table in database.
 *
 * @Type
 */
class User extends AbstractUser
{
}
