<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Model;

use doctrine\GraphQLite\Annotations\Type;

use App\Model\Generated\AbstractWallet;

/**
 * The Wallet class maps the 'wallets' table in database.
 * @Type
 */
class Wallet extends AbstractWallet
{
}
