import {StyleSheet} from 'react-native'
import Metrics from 'App/Theme/Metrics'
import Colors from 'App/Theme/Colors'
import Fonts from 'App/Theme/Fonts'
import ApplicationStyles from 'App/Theme/ApplicationStyles'

export default StyleSheet.create({
  addLocationText: {
    color: Colors.grey1,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.medium,
  },
  bottomBigContainer: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderTopLeftRadius: Metrics.applyRatio(25),
    borderTopRightRadius: Metrics.applyRatio(25),
    borderWidth: 0,
    elevation: 14,
    flex: 3,
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.1,
    shadowRadius: 9.11,
  },
  bottomBigText: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.max,
    fontStyle: 'normal',
    letterSpacing: 0,
    // fontWeight: 'bold',
    // marginVertical: Metrics.applyRatio(5),
  },
  bottomContainer: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    borderTopLeftRadius: Metrics.applyRatio(25),
    borderTopRightRadius: Metrics.applyRatio(25),
    borderWidth: 0,
    elevation: 14,
    flex: 2,
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.1,
    shadowRadius: 9.11,
  },
  circleIcon: {height: Metrics.applyRatio(15), width: Metrics.applyRatio(15)},
  container: {
    ...ApplicationStyles.screen.container,
    alignItems: 'center',
  },
  contentContainer: {
    flex: 5,
    position: 'relative',
  },
  descTxt: {
    color: Colors.grey,
    fontFamily: Fonts.fonts.PoppinsMedium,
    fontSize: Fonts.size.small,
    marginVertical: Metrics.applyRatio(8),
    textAlign: 'center',
    width: Metrics.applyRatio(263),
  },
  fabricIcon: {height: Metrics.applyRatio(25), width: Metrics.applyRatio(25)},
  footerListContainer: {
    width: Metrics.applyRatio(280),
  },
  gridItem: {
    alignItems: 'center',
    backgroundColor: Colors.white,
    flex: 1,
    paddingHorizontal: Metrics.applyRatio(5),
    paddingVertical: Metrics.applyRatio(10),
    textAlign: 'center',
  },
  handShakeIcon: {
    height: Metrics.applyRatio(14),
    width: Metrics.applyRatio(20),
  },
  headFlex: {flex: 0.2},
  headerContainer: {
    ...ApplicationStyles.screen.container,
    alignItems: 'center',
    flex: 1.5,
    justifyContent: 'center',
  },
  headerSubTitle: {
    ...Fonts.style.subSectionTitle,
    color: Colors.grey2,
    fontSize: Fonts.size.medium,
    marginVertical: Metrics.applyRatio(5),
    textAlign: 'center',
    width: Metrics.applyRatio(281),
  },
  headerTitle: {
    ...Fonts.style.title,
    marginVertical: Metrics.applyRatio(5),
    textAlign: 'center',
    width: Metrics.applyRatio(281),
  },
  innerPromoContent: {
    backgroundColor: Colors.white,
    borderRadius: Metrics.applyRatio(21),
    elevation: 14,
    marginBottom: Metrics.applyRatio(50),
    marginTop: Metrics.applyRatio(-50),
    padding: Metrics.applyRatio(20),
    position: 'relative',
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.1,
    shadowRadius: 9.11,
    width: Metrics.applyRatio(263),
    zIndex: 22,
  },
  leftContent: {
    justifyContent: 'flex-start',
  },
  listBottomSection: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: Metrics.applyRatio(8),
  },
  listBottomSectionText: {
    fontFamily: Fonts.fonts.PoppinsMedium,
    fontSize: Fonts.size.xsmall,
    paddingLeft: Metrics.applyRatio(5),
  },
  listButtonIcon: {
    ...ApplicationStyles.locationBoxThirdStyle,
  },
  listContentWrapper: {
    alignItems: 'center',
    marginTop: Metrics.applyRatio(10),
  },
  listImgWrapper: {
    borderRadius: Metrics.applyRatio(21),
    elevation: 14,
    height: Metrics.applyRatio(210),
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.1,
    shadowRadius: 9.11,
    width: Metrics.applyRatio(263),
  },
  listImgWrapperWithTopSpace: {
    borderRadius: Metrics.applyRatio(21),
    elevation: 14,
    height: Metrics.applyRatio(210),
    marginTop: Metrics.applyRatio(10),
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.1,
    shadowRadius: 9.11,
    width: Metrics.applyRatio(263),
  },
  listItemButtonList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginVertical: Metrics.applyRatio(10),
  },
  listTopSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: Metrics.applyRatio(7),
    paddingTop: Metrics.applyRatio(10),
  },
  listTopSectionIcon: {height: Metrics.applyRatio(18), width: Metrics.applyRatio(14)},
  listTopSectionText: {
    color: Colors.black1,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.bigMedium,
  },
  marginLeft: {
    marginLeft: Metrics.applyRatio(5),
  },
  marginRight: {
    marginRight: Metrics.applyRatio(5),
  },
  moreBtn: {
    color: Colors.black1,
    fontSize: Fonts.size.small,
    textAlign: 'right',
  },
  promoBgImg: {
    height: Metrics.applyRatio(384),
    width: Metrics.applyRatio(345),
  },
  promoContainer: {
    alignItems: 'center',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  promoImg: {
    borderRadius: Metrics.applyRatio(21),
    height: Metrics.applyRatio(210),
    width: Metrics.applyRatio(263),
    // shadowColor: Colors.black,
    // shadowOffset: {
    //     width: 0,
    //     height: 7,
    // },
    // shadowOpacity: 0.1,
    // shadowRadius: 9.11,
    // elevation: 14,
  },
  redemptionBottomCompleteTxt: {
    backgroundColor: Colors.green,
    borderRadius: Metrics.applyRatio(10),
    color: Colors.white,
    fontSize: Fonts.size.small,
    height: Metrics.applyRatio(20),
    paddingHorizontal: Metrics.applyRatio(8),
    paddingVertical: Metrics.applyRatio(3),
    textAlign: 'center',
  },
  redemptionBottomConetent: {
    alignItems: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
    top: Metrics.applyRatio(-14.5),
  },
  redemptionBottomTxt: {
    backgroundColor: Colors.black,
    borderRadius: Metrics.applyRatio(14.5),
    color: Colors.white,
    fontFamily: Fonts.fonts.PoppinsBold,
    fontSize: Fonts.size.small,
    fontStyle: 'normal',
    height: Metrics.applyRatio(29),
    letterSpacing: 0,
    paddingHorizontal: Metrics.applyRatio(8),
    paddingVertical: Metrics.applyRatio(6),
    textAlign: 'center',
  },
  redemptionCount: {
    alignItems: 'center',
    position: 'relative',
  },
  redemptionTxt: {
    backgroundColor: Colors.black,
    borderRadius: Metrics.applyRatio(19.5),
    color: Colors.white,
    fontSize: Fonts.size.small,
    marginTop: Metrics.applyRatio(-30),
    paddingHorizontal: Metrics.applyRatio(15),
    paddingVertical: Metrics.applyRatio(5),
    textAlign: 'center',
  },
  scrollContainer: {
    width: Metrics.applyRatio(345),
  },
  scrollContainerWithTopSpace: {
    marginTop: Metrics.applyRatio(20),
    width: Metrics.applyRatio(345),
  },
  shareIconSize: {
    height: Metrics.applyRatio(16),
    tintColor: Colors.white,
    width: Metrics.applyRatio(16),
  },
  shareView: {
    alignItems: 'center',
    backgroundColor: Colors.text,
    borderRadius: Metrics.applyRatio(23),
    height: Metrics.applyRatio(46),
    justifyContent: 'center',
    marginLeft: Metrics.applyRatio(20),
    width: Metrics.applyRatio(46),
  },
  subSectionTitle: {
    ...Fonts.style.promotionName,
    paddingLeft: Metrics.applyRatio(10),
  },
  textCenter: {
    color: Colors.greyishBrown,
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.small,
    fontStyle: 'normal',
    letterSpacing: 0,
    textAlign: 'center',
  },
  textCenterDescription: {
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.xsmall,
    textAlign: 'center',
  },
  topUp20: {
    marginTop: Metrics.applyRatio(-10),
    position: 'relative',
    zIndex: 2,
  },
  validationButton: {
    ...ApplicationStyles.buttonContainer,
    // marginVertical: Metrics.applyRatio(20),
  },
  validationText: {
    ...ApplicationStyles.textButton,
  },
  viewMoreTxt: {
    fontFamily: Fonts.fonts.PoppinsRegular,
    fontSize: Fonts.size.xsmall,
    textAlign: 'left',
  },
  waveImg: {
    height: Metrics.applyRatio(10),
    width: Metrics.applyRatio(49),
  },
})
