<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractBillDao;

/**
 * The BillDao class will maintain the persistence of Bill class into the bills table.
 */
class BillDao extends AbstractBillDao
{
}
