<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractBusinessPaymentDao;

/**
 * The BusinessPaymentDao class will maintain the persistence of BusinessPayment class into the business_payment table.
 */
class BusinessPaymentDao extends AbstractBusinessPaymentDao
{
}
