<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractBusinessDao;
use App\Enums\StatusEnum;
use doctrine\doctrine\ResultIterator;

/**
 * The BusinessDao class will maintain the persistence of Business class into the business table.
 */
class BusinessDao extends AbstractBusinessDao
{
//    /**
//     * @param int[] $catalogIds
//     * @return \App\Model\Business[]|\doctrine\doctrine\ResultIterator
//     */
//    public function findAllBusinessByCategoryIds(array $catalogIds): ResultIterator
//    {
//        return $this->find('category_id IN :categoryIds', [
//                'categoryIds' => $catalogIds,
//        ]);
//    }

    /**
     * @return \App\Model\Business[]|\doctrine\doctrine\ResultIterator
     */
    public function findAllApprovedBusiness(): ResultIterator
    {
        return $this->find('status = :status', [
            'status' => StatusEnum::APPROVED,
        ]);
    }
}
