<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCategoryDao;

/**
 * The CategoryDao class will maintain the persistence of Category class into the categorys table.
 */
class CategoryDao extends AbstractCategoryDao
{
}
