<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCustomerDao;
use App\Model\Customer;
use doctrine\doctrine\doctrineException;

/**
 * The CustomerDao class will maintain the persistence of Customer class into the customers table.
 */
class CustomerDao extends AbstractCustomerDao
{
    /**
     * @return Customer
     * @throws doctrineException
     */
    public function getambassadorCustomer(): Customer
    {
        return $this->getById(Customer::ambassador_ID);
    }
}
