<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractCustomerPaymentDao;

/**
 * The CustomerPaymentDao class will maintain the persistence of CustomerPayment class into the customer_payments table.
 */
class CustomerPaymentDao extends AbstractCustomerPaymentDao
{
}
