<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractDistrictDao;

/**
 * The DistrictDao class will maintain the persistence of District class into the districts table.
 */
class DistrictDao extends AbstractDistrictDao
{
}
