<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractMessageTranslationDao;

/**
 * The MessageTranslationDao class will maintain the persistence of MessageTranslation class into the message_translations table.
 */
class MessageTranslationDao extends AbstractMessageTranslationDao
{
}
