<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractOfflinePromoPricingDao;

/**
 * The OfflinePromoPricingDao class will maintain the persistence of OfflinePromoPricing class into the offline_promo_pricing table.
 */
class OfflinePromoPricingDao extends AbstractOfflinePromoPricingDao
{
}
