<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractOnlinePromoPricingDao;

/**
 * The OnlinePromoPricingDao class will maintain the persistence of OnlinePromoPricing class into the online_promo_pricing table.
 */
class OnlinePromoPricingDao extends AbstractOnlinePromoPricingDao
{
}
