<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPendingApplyHistoryRedemptionDao;

/**
 * The PendingApplyHistoryRedemptionDao class will maintain the persistence of PendingApplyHistoryRedemption class into the pending_apply_history_redemption table.
 */
class PendingApplyHistoryRedemptionDao extends AbstractPendingApplyHistoryRedemptionDao
{
}
