<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractPendingOnlineRedemptionDao;

/**
 * The PendingOnlineRedemptionDao class will maintain the persistence of PendingOnlineRedemption class into the pending_online_redemption table.
 */
class PendingOnlineRedemptionDao extends AbstractPendingOnlineRedemptionDao
{
}
