<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractRegionDao;

/**
 * The RegionDao class will maintain the persistence of Region class into the regions table.
 */
class RegionDao extends AbstractRegionDao
{
}
