<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractRoleRightDao;

/**
 * The RoleRightDao class will maintain the persistence of RoleRight class into the roles_rights table.
 */
class RoleRightDao extends AbstractRoleRightDao
{
}
