<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractSmSignInDao;

/**
 * The SmSignInDao class will maintain the persistence of SmSignIn class into the sms_sign_in table.
 */
class SmSignInDao extends AbstractSmSignInDao
{
}
