<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractSubCategoryDao;

/**
 * The SubCategoryDao class will maintain the persistence of SubCategory class into the sub_categories table.
 */
class SubCategoryDao extends AbstractSubCategoryDao
{
}
