<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractSubCategoryCustomerAverageSpendingDao;

/**
 * The SubCategoryCustomerAverageSpendingDao class will maintain the persistence of SubCategoryCustomerAverageSpending class into the sub_category_customer_average_spending table.
 */
class SubCategoryCustomerAverageSpendingDao extends AbstractSubCategoryCustomerAverageSpendingDao
{
}
