<?php
/*
 * This file has been automatically generated by doctrine.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Dao;

use App\Dao\Generated\AbstractTransactionDao;

/**
 * The TransactionDao class will maintain the persistence of Transaction class into the transactions table.
 */
class TransactionDao extends AbstractTransactionDao
{
}
